services:

  db:
    image: postgres:15
    container_name: estoque_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 595690
      POSTGRES_DB: estoque_db
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  api:
    build: .
    container_name: estoque_api

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"